server:
  port: 8021

spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 192.168.1.104:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public